# name: Log Stock of Stonks Data

# on:
#   schedule:
#     - cron: '*/5 * * * *'  # Runs every 5 minutes
#   workflow_dispatch:

# jobs:
#   log-data:
#     runs-on: ubuntu-latest
#     timeout-minutes: 360  # Set the timeout to 6 hours

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4
#       with:
#         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.x'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run script
#       env:
#         HYPIXEL_API_KEY: ${{ secrets.HYPIXEL_API_KEY }}
#       run: python datalog.py

#     - name: Configure Git
#       run: |
#         git config --global user.name 'github-actions[bot]'
#         git config --global user.email 'github-actions[bot]@users.noreply.github.com'

#     - name: Commit and Push Changes
#       env:
#         GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#       run: |
#         git add STOCK_OF_STONKS_price_history.csv
#         git commit -m "Update STOCK_OF_STONKS_price_history.csv"
#         git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
